# -*- coding: utf-8 -*-
"""11w_book_crawling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1maMQ246JzOwCdgg9xr1vpm2-ghacvNgX
"""

import urllib.request as req
from bs4 import BeautifulSoup
f = open("./1조_노혜주_출력결과.txt", "w")

week_num = 1
ranking=1
while True:
  code = req.urlopen("https://www.aladin.co.kr/shop/common/wbest.aspx?BranchType=1&CID=0&Year=2022&Month=1&Week={}&BestType=Bestseller&SearchSubBarcode=".format(week_num))
  soup = BeautifulSoup(code, "html.parser")
  
  title = soup.select("a.bo3 > b")
  
  if week_num == 6:
    break

  for i in range(len(title)): 
    print(f'{week_num}주차 {ranking}위 {title[i].string}')
    f.write(f'{week_num}주차 {ranking}위 {title[i].string} \n')
    ranking +=1
  week_num += 1
  ranking=1
f.close()